# This file contains all Packet IDs

ERR = "ERR"
ERR_SHIP_DESTROYED = 1
ERR_SERVERID_OR_MAPID_WRONG = 8
ERR_INVALID_SID = 41

CREATE_STATION = "s"
CREATE_PORTAL = "p"
CREATE_SHIP = "C"
CREATE_BOX = "c"

REMOVE_BOX = "2"


HERO_INIT = "I"
HERO_POSITION_UPDATE = "D"

NEW_MAP = "m"
LOG_MESSAGE = "LM"
SHIP_MOVEMENT = "1"
SET_STATUS = "S"
